### ISSUE TITLE
Incorrect behaviour for comments

### ISSUE THREAD

**Issue by JAD-SVK** [superaitaotao/BTLint#1]
When I activated the **BTLint** *(downloaded today)* in Visual Studio 2015 I got more than 630 warnings *(the application was already scanned with 4 other lint-like tools, with and has less than 80 warning suppressions for all the tools, where almost all rules are enabled)*.  That means that **BTLint** is too strict and/or has too many false positives.

One example is line of comment that begins with word `unless`. The result is:

```
Warning	BTLint	Capital letter first
Warning	BTLint	First verb may not be in -s -es 
```

Both are on the same word in comment: "unless". As far as I know *(and the spell-checker work)* this is a correct word in English language. Therefore the second warning is definitely a false positive.

The first... I'm not sure. Since I'm not a native a English speaker, I do not know, whether each line in text must begin with a capital letter. *(Independent whether the previous line has a coma, end of sentence.)*

It would be good to have more specific error codes *(e.g. BT0012)* and have the option to configure active and inactive rules. In this state, is the **BTLint**, unfortunately, unusable for me. It request comments even for private constants, where the constant name is already a help. And the only selection is: 'enable all rules' or 'disable all rules'.

**Comment by superaitaotao** [comment]
Hi, thank you so much for using the plugin!!!
You are absolutely correct that the rules are too strict as my company's code guideline is very strict.
So I am afraid that this may not be applicable to every user/company.
But you are right that allowing the user to pick the rules is a great feature to have.
Unfortunately, I am quite busy these days that I don't think I will have time to work on that any time soon.
